on: [push, pull_request]

name: Build, Test and Codecov

jobs:
  build:
    name: Build, Test and Codecov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Push build to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: build project"
          default_author: github_actions

      - name: Test project
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info,./coverage/clover.xml
